authors:
  aisrael:
    name: Adam Israel
    display_name: Adam Israel
    gravatar: a5ffaae8e4892a1b6ef450a7a701861d
    web: http://adamisrael.com
    email: adam@adamisrael.com
    twitter: adamisrael
    github: AdamIsrael
  mceppi:
    name: Marco Ceppi
    display_name: Marco Ceppi
    gravatar: 4ddc8924e79bcec03256821af65fca91
    email: marco@ceppi.net
    web: http://marcoceppi.com
    twitter: marcoceppi
    github: marcoceppi
